Adds initial file sync

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -5,11 +5,54 @@
 #
 # This is free software with ABSOLUTELY NO WARRANTY.
 
+source "${HOME}/.dotfiles/lib/logger";
 source "${HOME}/.dotfiles/lib/mkdirs";
+source "${HOME}/.dotfiles/lib/setfile";
 
-echo "Hello from dotfiles.";
+log_info "Symlinking files to ${HOME}...";
 
-mkdirs "${HOME}/Projects";
-mkdirs "${HOME}/.git-templates/hooks";
+declare -a home_files=(
+  'home/aliases'
+  'home/bash_config'
+  'home/bashrc'
+  'home/completions'
+  'home/hushlogin'
+  'home/inputrc'
+  'home/paths'
+  'home/profile'
+  'home/prompt'
+  'home/vimrc'
+);
 
-! [ -z "$(type -P git)" ] && install_git;
+# Link home dotfiles files.
+for home_file in "${home_files[@]}"; do
+  [[ -f "${home_file}" ]] && setfile "${home_file}" "${HOME}/.$(basename $home_file)";
+done;
+
+# Link function files.
+mkdirs "${HOME}/.functions";
+if [[ $? ]]; then
+  for function_file in home/functions/*; do
+    [[ -f "${function_file}" ]] && setfile "${function_file}" "${HOME}/.functions/$(basename $function_file)";
+  done;
+else
+  log_error "Could not create ${HOME}/.functions"
+fi
+
+# Link commands into PATH.
+for bin_file in home/bin/*; do
+  [[ -f "${bin_file}" ]] && setfile "${bin_file}" "${HOME}/.bin/$(basename $bin_file)";
+done;
+
+# Always copy editorconfig (can't remember why).
+rsync -avz --quiet 'home/editorconfig' "${HOME}/.editorconfig";
+
+# Create dotfiles.local if not present.
+if [[ ! -r "${HOME}/.dotfiles.local" ]]; then
+  log_info "Creating ${HOME}/.dotfiles.local";
+  printf '#!/bin/bash\n\n' >> "${HOME}/.dotfiles.local";
+fi;
+
+# Source bashrc to make sure the environment is set before moving on.
+source "${HOME}/.bashrc";
+log_success "Done.";
