Incorporates utils helper functions into init

diff --git a/init b/init
--- a/init
+++ b/init
@@ -4,8 +4,24 @@ DOTFILES_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
 DOTFILES_GIT_REMOTE="https://github.com/goodguyry/dotfiles"
 
 
-# Helper functions
-source "$DOTFILES_DIRECTORY/lib/utils";
+# Logging helpers
+# By Necolas Gallagher
+# https://github.com/necolas/dotfiles/blob/master/lib/utils
+log_header() {
+  printf "\n$(tput setaf 7)%s$(tput sgr0)\n" "$@"
+}
+
+log_success() {
+  printf "$(tput setaf 64)✓ %s$(tput sgr0)\n" "$@"
+}
+
+log_error() {
+  printf "$(tput setaf 1)x %s$(tput sgr0)\n" "$@"
+}
+
+log_warning() {
+  printf "$(tput setaf 136)! %s$(tput sgr0)\n" "$@"
+}
 
 
 # Help text
@@ -60,7 +76,7 @@ do
                -c)  COPY_FILES=true ;;
          --server)  SERVER=true; NO_PACKAGES=true ;;  # Skip OS X-related packages/settings
                -s)  SERVER=true; NO_PACKAGES=true ;;
-           -*|--*)  e_warning "Warning: invalid option $opt" && show_help && exit ;;
+           -*|--*)  log_warning "Warning: invalid option $opt" && show_help && exit ;;
   esac
 done;
 
@@ -77,27 +93,27 @@ mkdirs "$HOME/.bin";
 
 # Conditionally install Command Line Tools, Homebrew and Git
 if [[ $NO_PACKAGES ]]; then
-  e_header "Skipping Homebrew and Git installations.";
+  log_header "Skipping Homebrew and Git installations.";
 else
   # Before relying on Homebrew, check that packages can be compiled
-  if ! type_exists 'gcc'; then
-    e_error "The XCode Command Line Tools must be installed first.";
+  if [ ! $(type -P gcc) ]; then
+    log_error "The XCode Command Line Tools must be installed first.";
     xcode-select --install;
   fi;
 
   # Check for Homebrew
-  if ! type_exists 'brew'; then
-    e_header "Installing Homebrew...";
+  if [ ! $(type -P brew) ]; then
+    log_header "Installing Homebrew...";
     ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
     brew doctor;
-    [[ $? ]] && e_success "Homebrew installed.";
+    [[ $? ]] && log_success "Homebrew installed.";
   fi;
 
   # Check for git
-  if ! type_exists 'git'; then
-    e_header "Updating Homebrew...";
+  if [ ! $(type -P git) ]; then
+    log_header "Updating Homebrew...";
     brew update;
-    e_header "Installing Git...";
+    log_header "Installing Git...";
     brew install git;
     ln -sf "$(brew --prefix)/share/git-core/contrib/diff-highlight/diff-highlight" "$HOME/.bin/diff-highlight";
   fi;
@@ -105,11 +121,11 @@ fi;
 
 
 # Conditionally init and pull the Git repo
-if [[ ! $COPY || ! $SERVER ]] && type_exists 'git' ; then
+if [[ ! $COPY || ! $SERVER ]] && [ $(type -P git) ] ; then
   cd "$DOTFILES_DIRECTORY";
   # Initialize the git repository if it's missing
-  if ! is_git_repo; then
-    e_header "Initializing git repository...";
+  if ! $(git rev-parse --is-inside-work-tree &> /dev/null); then
+    log_header "Initializing git repository...";
     git init;
     git remote add origin $DOTFILES_GIT_REMOTE;
     git fetch origin master;
@@ -117,20 +133,20 @@ if [[ ! $COPY || ! $SERVER ]] && type_exists 'git' ; then
     git reset --hard FETCH_HEAD;
     # Remove any untracked files
     git clean -fd;
-    e_header "Syncing dotfiles...";
+    log_header "Syncing dotfiles...";
     # Pull down the latest changes
     git pull --rebase origin master;
   else
-    e_header "Already a Git repo.";
+    log_header "Already a Git repo.";
   fi;
 else
-  e_header "Skipping 'git init'";
+  log_header "Skipping 'git init'";
 fi;
 
 
 # Sets the dotfiles in place in the `HOME` directory.
 function set_files() {
-  e_header "Setting files...";
+  log_header "Setting files...";
 
   # Helper function
   # Conditionally symlink or copy the files
@@ -191,25 +207,25 @@ function set_files() {
   if [[ ! -r "$HOME/.vim/colors/solarized.vim" ]]; then
     if [[ $SERVER ]]; then
       # Extract colors/solarized.vim into .vim (Linux-friendly)
-      e_header "Downloading Solarized Vim theme...";
+      log_header "Downloading Solarized Vim theme...";
       curl -#L https://github.com/altercation/vim-colors-solarized/tarball/master | tar -xzv -C "$HOME/.vim" --strip-components 1 --wildcards **/solarized.vim;
     else
       # Extract colors/solarized.vim into .vim (OS X-Friendly)
-      e_header "Downloading Solarized Vim theme...";
+      log_header "Downloading Solarized Vim theme...";
       curl -#L https://github.com/altercation/vim-colors-solarized/tarball/master | tar -xzv -C "$HOME/.vim" --strip-components 1 --include="**/solarized.vim";
     fi;
-    [[ $? ]] && e_success "Solarized theme installed";
+    [[ $? ]] && log_success "Solarized theme installed";
   else
-    e_header "Solarized theme already installed.";
+    log_header "Solarized theme already installed.";
   fi;
 
-  e_success "Dotfiles update complete!";
+  log_success "Dotfiles update complete!";
 }
 
 
 # Ask before potentially overwriting files
 printf "\n";
-e_warning "Warning: This step may overwrite your existing dotfiles.";
+log_warning "Warning: This step may overwrite your existing dotfiles.";
 printf "Continue? [Y/n]";
 read CONTINUE;
 printf "\n";
@@ -217,7 +233,7 @@ printf "\n";
 
 # Conditionally set the dotfiles in place
 if [[ "$CONTINUE" == "n" ]]; then
-  e_header "Aborting...";
+  log_header "Aborting...";
   exit 1;
 else
   set_files;
@@ -238,7 +254,7 @@ source "$HOME/.bashrc";
 
 # Conditionally install packages
 if [[ $NO_PACKAGES ]]; then
-  e_header "Skipping package installation...";
+  log_header "Skipping package installation...";
 else
   # Install Homebrew packages
   source bin/brews;
@@ -250,9 +266,9 @@ else
   # Change to bash 4 installed by bin/brews
   if [[ ! $(grep "/usr/local/bin/bash" /etc/shells) ]]; then
     echo /usr/local/bin/bash|sudo tee -a /etc/shells && chsh -s /usr/local/bin/bash;
-    e_success "Shell switched to Bash 4";
+    log_success "Shell switched to Bash 4";
   else
-    e_header "/usr/local/bin/bash already in /etc/shells";
+    log_header "/usr/local/bin/bash already in /etc/shells";
   fi;
 fi;
 
@@ -260,7 +276,7 @@ fi;
 if [[ ! $SERVER ]]; then
   # Ask before potentially overwriting files
   printf "\n";
-  e_warning "Warning: This step may modify your OS X system defaults.";
+  log_warning "Warning: This step may modify your OS X system defaults.";
   printf "Continue? [Y/n]";
   read SET_OSX;
   printf "\n";
@@ -268,7 +284,7 @@ if [[ ! $SERVER ]]; then
 
   # Conditionally set defaults
   if [[ "$SET_OSX" == "n" ]]; then
-    e_header "Skipped OS X settings update.";
+    log_header "Skipped OS X settings update.";
   else
     source bin/osx;
   fi;
@@ -278,6 +294,6 @@ fi;
 unset COPY_FILES;
 
 
-[[ $? ]] && e_success "Restarting the shell to apply changes";
+[[ $? ]] && log_success "Restarting the shell to apply changes";
 
 exec $SHELL -l;
