Logging updates

diff --git a/init b/init
--- a/init
+++ b/init
@@ -47,7 +47,6 @@ print_script_details;
 printf '\n';
 printf 'Continue? [Y/n]';
 read CONTINUE;
-printf '\n';
 
 # Conditionally set the dotfiles in place.
 if [[ "${CONTINUE}" == 'n' ]]; then
@@ -64,9 +63,9 @@ if $INSTALL_PACKAGES; then
   if $SYNC_REPO; then
     # Initialize the git repository if it's missing.
     if $(git rev-parse --is-inside-work-tree &> /dev/null); then
-      log_header 'Already a Git repo.';
+      log_info 'Dotfiles directory is already a Git repo.';
     else
-      log_header 'Initializing git repository...';
+      log_info 'Syncing dotfiles...';
       git init;
       git remote add origin "${DOTFILES_GIT_REMOTE}";
       git fetch origin master;
@@ -74,24 +73,18 @@ if $INSTALL_PACKAGES; then
       git reset --hard FETCH_HEAD;
       # Remove any untracked files.
       git clean -fd;
-      log_header 'Syncing dotfiles...';
       # Pull down the latest changes.
       git pull --rebase origin master;
     fi;
   fi;
-else
-  log_header "Skipping Homebrew and Git";
 fi
 
 # Add git config settings.
 if [[ $CONFIGURE_PREFERENCES && $HAS_GIT ]]; then
-  log_header "Configuring Git...";
-
   source bin/gitconfig;
-  [[ $? ]] && log_success "Git configuration applied" || log_error 'There was a problem configuring Git.';
 fi;
 
-log_header "${WRITE_VERB}ing files to ${HOME}..."
+log_info "${WRITE_VERB}ing files to ${HOME}..."
 
 mkdirs '.git-templates/hooks';
 
@@ -115,12 +108,14 @@ rsync -avz --quiet 'home/editorconfig'         "${HOME}/.editorconfig";
 
 # Create dotfiles.local if not present.
 if [[ ! -r "${HOME}/.dotfiles.local" ]]; then
-  log_header "Creating ${HOME}/.dotfiles.local";
+  log_info "Creating ${HOME}/.dotfiles.local";
   printf '#!/bin/bash\n\n' >> "${HOME}/.dotfiles.local";
 fi;
 
 # Source bashrc to make sure the environment is set before moving on.
 source "${HOME}/.bashrc";
+log_success "Done.";
+printf "\n";
 
 if $INSTALL_PACKAGES; then
   install_homebrew;
@@ -166,9 +161,9 @@ if $INSTALL_PACKAGES; then
 
   # Download the Solarized Vim theme.
   if [[ -f "${HOME}/.vim/colors/solarized.vim" ]]; then
-    log_header 'Solarized Vim theme already installed.';
+    log_info 'Solarized Vim theme already installed.';
   else
-    log_header 'Downloading Solarized Vim theme...';
+    # log_info 'Downloading Solarized Vim theme...';
     # Extract colors/solarized.vim into .vim (Linux-friendly).
     if $IS_LINUX; then
       # Linux-friendly.
@@ -179,28 +174,23 @@ if $INSTALL_PACKAGES; then
       curl -#L https://github.com/altercation/vim-colors-solarized/tarball/master | \
         tar -xzv -C "${HOME}/.vim" --strip-components 1 --include='**/solarized.vim';
     fi;
-    [[ $? ]] && log_success 'Solarized Vim theme installed';
+    [[ $? ]] && log_success 'Solarized Vim theme installed' || log_error 'There was a problem installing the Solarized Vim theme.';
   fi;
 fi;
 
 if $CONFIGURE_PREFERENCES; then
   # Ask before potentially overwriting files.
-  printf '\n';
   log_warning "Warning: This step may modify your ${PROVISION_ENV} system defaults.";
   printf 'Continue? [Y/n] ';
   read DO_PREFERENCES;
   printf '\n';
 
   # Conditionally set defaults.
-  if [[ "${DO_PREFERENCES}" == 'n' ]]; then
-    log_header "Skipped configuring ${PROVISION_ENV} preferences.";
-  else
+  if [[ "${DO_PREFERENCES}" =~ ^[yY]$ ]]; then
     $IS_MACOS && source bin/macos;
     # $IS_LINUX && source bin/linux-desktop;
     # $IS_SERVER && source bin/linux-server;
   fi;
-else
-  log_header "Skipped configuring ${PROVISION_ENV} preferences.";
 fi;
 
 unset DOTFILES_DIRECTORY;
@@ -216,6 +206,7 @@ unset HAS_GIT;
 unset PROVISION_ENV;
 unset WRITE_VERB;
 
-[[ $? ]] && log_success 'Restarting the shell to apply changes';
+[[ $? ]] && log_success 'Done. Restarting the shell to apply changes...';
+printf "\n";
 
 exec $SHELL -l;
