Syncs lib files to ~/.dotfiles/lib/

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -40,8 +40,19 @@ ln -sf "${dotfiles_root}/dotfiles" "${HOME}/.bin/dotfiles";
 
 mmkd "${HOME}/.dotfiles";
 if [[ $? ]]; then
+  # Sync subcommands into place.
   for subcommand_file in "${dotfiles_root}"/bin/*; do
     [[ -f "${subcommand_file}" ]] && setfile "${subcommand_file}" "${HOME}/.dotfiles/$(basename "${subcommand_file}")";
+  done;
+else
+  status --error "Could not create ${HOME}/.dotfiles";
+fi
+
+mmkd "${HOME}/.dotfiles/lib";
+if [[ $? ]]; then
+  # Sync lib files to ~/.dotfiles/lib/
+  for lib_file in "${dotfiles_root}"/lib/*; do
+    [[ -f "${lib_file}" ]] && setfile "${lib_file}" "${HOME}/.dotfiles/lib/$(basename "${lib_file}")";
   done;
 else
   status --error "Could not create ${HOME}/.dotfiles";
